---
name: code-lint
run-name: "${{ github.actor }} has triggered the ${{ github.workflow }} workflow"
on:
  pull_request:
    types:
      - unlabeled
      - labeled
      - synchronize
      - opened
      - reopened
      - edited
permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: write
  issues: write
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false
jobs:
  # action-lint:
  #   name: actions-lint
  #   uses: nkbinnovations/reusable-workflows/.github/workflows/github-action-lint.yaml@v1 # best to use the SHA instead of tags for immutable code.
  terraform-lint:
    name: terraform-lint
    # needs:
    #   - github-action-lint
    uses: nkbinnovations/reusable-workflows/.github/workflows/github-terraform-lint.yaml@nandakumar649-patch-1 # best to use the SHA instead of tags for immutable code.
    with:
      terraform_version: '1.10.3'
      terraform_directory: "."