---
name: code-lint
run-name: "${{ github.actor }} has triggered the ${{ github.workflow }} workflow"
on:
  pull_request:
    types:
      - unlabeled
      - labeled
      - synchronize
      - opened
      - reopened
      - edited
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}  # This is the concurrency group name and should be unique per pull request
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}  # Cancel previous runs if a new run is triggered on a non-release branch
jobs:
  github-action-lint:
    name: githu-actions-lint
    uses: nkbinnovations/reusable-workflows/.github/workflows/github-action-lint.yaml@v1 # best to use the SHA instead of tags for immutable code.
  github-terraform-lint:
    name: terraform-lint
    uses: nkbinnovations/reusable-workflows/.github/workflows/github-terraform-lint.yaml@v1 # best to use the SHA instead of tags for immutable code.
    with:
      terraform_version: '1.10.3'